### ISSUE TITLE
Support for chinese

### ISSUE THREAD

**Issue by cosmoschen94** [csurfer/rake-nltk#15]
Does rake-nltk fully support Chinese in the newest version?

**Comment by csurfer** [comment]
@cosmoschen94 : I don't believe nltk at the moment supports chinese stopwords and tokenization. As this package depends on nltk for tokenization and stopwords the package doesn't support chinese at the moment.

If I am wrong and nltk does support chinese tokenization please provide me with the link and the required details and I will add details of how to make it work to the README.

**Comment by fighting41love** [comment]
I have modified the codes which can support the Chinese now. I will upload the code to a repo soon.

**Comment by Jiannan28** [comment]
Do we have chinese support now? or it's in another package? Thanks.
