### ISSUE TITLE
Losing the context of phrase

### ISSUE THREAD

**Issue by sairajh** [csurfer/rake-nltk#16]
not and other negation words are currently part of the stopword list which is thus not detected as  a part of the keyphrase. This in turn changes the context of the keyphrase.
for eg - This is not one of the best places i have been to
keyphrase - best place

**Comment by csurfer** [comment]
@sairajh : You can provide your own list of stopwords if the list of default stopwords is not suitable for your purpose.

You can even re-use the nltk stopwords and append your own list and use to combination list as your list of stopwords.
