### ISSUE TITLE
Language selection

### ISSUE THREAD

**Issue by digvijayv** [csurfer/rake-nltk#17]
When i am selecting some other language in rake then it is not identifying keyphrase rather its throwing the whole sentence as an key phrase.

**Comment by birm** [comment]
Are you able to post a snippet/gist with the code you're using and the output?

**Comment by juggernauts** [comment]
`from rake_nltk import Rake

r = Rake("german") 
text = "Weitere Luftschläge gegen syrische Stellungen würden \"unweigerlich Chaos\" verursachen, droht Russlands Präsident Putin. Frankreich will den Konflikt jetzt mit einer neuen Uno-Resolution entschärfen."

r.extract_keywords_from_text(text)

print r.get_ranked_phrases() # To get keyword phrases ranked highest to lowest.`

The above code produces the following output:
`['frankreich will den konflikt jetzt mit einer neuen uno', 'weitere luftschlge gegen syrische stellungen wrden', 'droht russlands prsident putin', 'unweigerlich chaos', 'resolution entschrfen', 'verursachen']`

It seems like for languages other than English, it is not removing stopwords at all!

**Comment by csurfer** [comment]
@juggernauts : When you use the API as `r = Rake("german")` you are not actually using the API with language set to german. You need to use it as `r = Rake(language="german")` to get that set. i,e Language is not the first parameter to the API. Please use as above and it will work as advertised.
