### ISSUE TITLE
Feature suggestion -- alternative word scoring metrics

### ISSUE THREAD

**Issue by drussellmrichie** [csurfer/rake-nltk#19]
First, great package. Very easy to use!

May I kindly suggest/request a feature? In the RAKE paper, they say that there are multiple ways to compute word scores, each of which favor different kinds of key phrases:

1. word frequency (freq(w))
2. word degree (deg(w)),
3. ratio of degree to frequency (deg(w)/freq(w))

The third is what they primarily use and is what your package uses. However, as Rose et al note, this metric favors longer keyphrases. Indeed, in my dataset of news articles, I find that this produces very wonky, idiosyncratic phrases that don't, impressionistically, describe my articles well.

So it could be nice to allow something like the following:

`r = Rake(metric='word_freq')`

when initializing the Rake object.

I would help with this but I don't really know Python OOP...

**Comment by csurfer** [comment]
@drussellmrichie: That's a really neat idea. I will try to get it soon enough.

**Comment by csurfer** [comment]
@drussellmrichie : Please update the package to 1.0.3 and you should have the feature to change the ranking metric between d(w)/f(w) or d(w) or f(w)
