### ISSUE TITLE
Incorporate stopwords in keyword extraction

### ISSUE THREAD

**Issue by Ravenclaw968** [csurfer/rake-nltk#20]
Hello and first of all great API,

Is there a way to allow the incorporation of stopwords and punctuation in the keyword analysis?

Thanks!

**Comment by csurfer** [comment]
We use stopwords from the language if none is given. When stopwords and punctuation are given we use that instead. So give the stopwords and punctuation but give a word/punctuation not in the text you are using but also not one of the stopwords. That should work for you I guess.
