### ISSUE TITLE
exception: no description

### ISSUE THREAD

**Issue by vishal-chandra** [csurfer/rake-nltk#29]
![image](https://user-images.githubusercontent.com/32851317/47673062-ee4fa680-db89-11e8-8bd9-1f63f2726b78.png)
What is causing this to happen? This is just the code from the README

**Comment by salehhoushangi** [comment]
Hi Vishal
This error  occurs  for me when I try   to using "raise"  to exception handling  my code  . so instead of using raise ValueError i used raise ValueError("Error1") to resolved it .
