### ISSUE TITLE
What is the relationship between the usage and rake.py?

### ISSUE THREAD

**Issue by Poppy856** [csurfer/rake-nltk#3]
Hi~ I am a student who study rake firstly. When I tried to extract the key phrases, I could just use the commands in your "Usage" without run rake.py. So I am really confused about that, so I want to ask how can I run rake.py and extract key phrases? My question may be a little silly, but i am really interested in this implementation. Best wishes.

**Comment by csurfer** [comment]
This is released as  a package in `PyPi`. So use the setup instructions to install it using `pip`. If you do not want to do that, use the setup instructions using repository. Once you have installed this package you can extract key words as shown in the usage section.

**Comment by Poppy856** [comment]
I see, thanks a lot!!
