### ISSUE TITLE
get no results

### ISSUE THREAD

**Issue by yclin925** [csurfer/rake-nltk#35]
I use the simply code from demo like 
`from rake_nltk import Rake

r = Rake()
mytext = "Hello World!"

r.extract_keywords_from_text(mytext)
r.get_ranked_phrases()`

but no any results were output. Is the python version issue?(use 3.6)
`In [19]: runfile('C:/Users/yclin57/AI_summary_test.py', wdir='C:/Users/yclin57')
In [20]:
`

**Comment by yclin925** [comment]
Update the test result today, i could run the code with jupyter but no result with Spyder.

**Comment by csurfer** [comment]
@yclin925 : It is supported on Python3.6. Can you please run it again and provide all information possible?

**Comment by yclin925** [comment]
![rake](https://user-images.githubusercontent.com/46888470/51676290-25aae380-2011-11e9-9c2e-f7d014b080a1.JPG)

I use spyder run rake-nltk but no result return as attachment. Was my computer issue? many thanks

**Comment by limesun** [comment]
I have the same issue here with Python 3.5

**Comment by yclin925** [comment]
I've fund the solution. Use 'print(r.get_ranked_phrases())' can solve the problem when use spyder.
