### ISSUE TITLE
Max words missing

### ISSUE THREAD

**Issue by hmilkovi** [csurfer/rake-nltk#4]
Thx for your project, the only thing I'm missing is the max word limit.
I had one project that I had to specify it but couldn't without overwriting
so I used other open source rake project.
Thx.

**Comment by wangtianyiftd** [comment]
> so I used other open source rake project

hi, @hmilkovi which rake project do you use?  I think I also need the max words limit.
thank you.

**Comment by csurfer** [comment]
@hmilkovi  @wangtianyiftd: Can you guys specify the max word limit requirement in detail, please 
? If either of you could raise a pull request for the same it would be awesome. But if not specifying the detail would help me get to it and implement it when time permits.

**Comment by hmilkovi** [comment]
@wangtianyiftd I use for now this repo: https://github.com/aneesha/RAKE
@csurfer Yes I will over the weekend and contribute to this repo, as I really like the
simplicity of use.

**Comment by TinaHongBu** [comment]
I am also interested in the max words feature. Is there any update?

**Comment by rakeshmahadasa** [comment]
Excuse me @TinaHongBu, Could you please explain what the max words feature that you are talking about is ?? I would be very happy to work on that and contribute to the repo. please take some time and let us know about the details and I will start working on that right away. Thanks

**Comment by geoffrey-eisenbarth** [comment]
@rakeshmahadasa I think the idea is that currently using ``r.get_ranked_phrases()`` returns phrases of any length, which in the few examples I've run are often 4+ words long. It'd be nice if it were possible to get the ranked phrases that are no longer than, say, 2 words long. 

This could be done after running your package with a line like
``filtered_results = [phrase for phrase in r.get_ranked_phrases() if len(phrase.split(' ')) < MAX_PHRASE_LENGTH]``, for some ``MAX_PHRASE_LENGTH``, say ``3`` or so. 

I don't know if there's a way to implement this in a way to not do all the calculations involved in ``r.extract_keywords_from_text()`` and then filtering the results. 

Thoughts?

**Comment by csurfer** [comment]
With @LetianFeng's PR being merged, repository now has the capability to cater to min and max word settings for Rake. Should be part of v1.0.4+
