### ISSUE TITLE
Add Brazilian Portuguese language support

### ISSUE THREAD

**Issue by johnidm** [csurfer/rake-nltk#6]
Hi @csurfer

What do you think of including support for Brazilian Portuguese?

I can to do this :-)

**Comment by csurfer** [comment]
@johnidm: As long as nltk has stopwords for that language, punctuation information and tokenizer using it with any language should be the same. You can raise a pull request to ensure the program handles different languages gracefully. 

Forcing download of any language apart from en or es seems forced. We can create a param in class constructor to take the language information and let the users download what ever language pickle they want. Just my two cents.

**Comment by johnidm** [comment]
Thanks for information @cgratie 

I will start to work on

**Comment by johnidm** [comment]
Examples for Portuguese Processing - http://www.nltk.org/howto/portuguese_en.html
