### ISSUE TITLE
clarity regarding score returned

### ISSUE THREAD

**Issue by kamrapooja** [csurfer/rake-nltk#65]
We are using get_ranked_phrases_with_scores to get the key phrases and ranking score. for our examples the api is returning 2750 key phrases as we have lengthy paragraph. In the output we are getting ranking score as well. What is the meaning of score and can we ignore some key phrases depend on score given? And if yes, then what ranking score we should consider to ignore key phrases

**Comment by jmorenoven2** [comment]
Hello. In order to understand the scoring, read the paper of Rose, et.al about RAKE Keyword Extraction. It is beautifully explained.
Regarding the list of results, of course you can crop the list from a certain score to get rid of the rubbish with score = 1.
AND you should do your own stopword list
