### ISSUE TITLE
About Spanish

### ISSUE THREAD

**Issue by chikiuso** [csurfer/rake-nltk#8]
Hi, may I ask about the workthrough to use Spanish rake? thanks.

**Comment by AliceLee1203** [comment]
Have you found the solution yet?
I met the same problem in Chinese.

**Comment by AxelAli** [comment]
You could download the spanish ntlk file.
for example , i use
`r = Rake(language='portuguese') `
for portuguese!

**Comment by csurfer** [comment]
@chikiuso : @AxelAli is right. As long as nltk can tokenize the sentences in the language of your choice (which here is Spanish, which I do believe it does) you can create object using

```python
r = Rake(language='spanish')
```

or you can provide your own stopwords and punctuation set to the object as

```python
r = Rake(stopwords=<list of stopwords>, punctuations=<list of punctuations>)
```

and hence completely eliminate the need for providing the language. But do know that as the tokenizer still needs to know how to tokenize a language, if nltk doesn't support a particular language this package also wont.
